version: 0.2

phases:
  install:
    commands:
      - echo "Installing Python dependencies..."
      - pip3 install -r requirements.txt -t .
  build:
    commands:
      - echo "Build is complete."
artifacts:
  files:
    - '**/*'
